source 'https://rubygems.org'

gem 'rails',                '4.2.0'               # A web-application framework to create database-backed web applications
gem 'sass-rails',           '~> 5.0'              # Use SCSS for stylesheets
gem 'uglifier',             '>= 1.3.0'            # Use Uglifier as compressor for JavaScript assets
gem 'coffee-rails',         '~> 4.1.0'            # Use CoffeeScript for .coffee assets and views
gem 'jquery-rails',         '4.0.3'               # Use jquery as the JavaScript library
gem 'jquery-turbolinks',    '2.1.0'               # Trigger js properly on jquery page loads
gem 'turbolinks',           '2.5.3'               # Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'bootstrap-sass',       '3.3.3'               # Sass-powered version of Bootstrap
gem 'autoprefixer-rails',   '5.1.3'               # recommended to use Autoprefixer with Bootstrap to add browser vendor prefixes automatically
gem 'font-awesome-rails',   '4.3.0'               # Font-Awesome web fonts and stylesheets as a Rails engine for use with the asset pipeline
gem 'jbuilder',             '~> 2.0'              # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'devise',               '3.4.1'               # Flexible authentication solution for Rails based on Warden
gem 'puma',                 '2.11.0'              # Use Puma as the app server
gem 'seedbank',             '0.3.0'               # Seedbank allows you to structure your Rails seed data
gem 'rails-api',            '0.4.0'               # A subset of a normal Rails application, created for applications that don't require all functionality that a complete Rails application provides
gem 'prmd',                 '0.7.0'               # JSON Schema tooling for describing an API
gem 'responders',           '2.1.0'               # respond_with and the corresponding class-level respond_to have been moved to this gem
gem 'friendly_id',          '5.1.0'               # It lets you create pretty URLs and work with human-friendly strings as if they were numeric ids.

gem 'feedjira',             '1.6.0'               # RSS and Atom feed parser
gem 'ruby-readability',     '0.7.0'               # Library for Readability service, which simplifies web pages etc
gem 'paperclip',            '4.2.1'               # External storage for images
gem 'sidekiq',              '3.3.2'               # Background worker classes for parallel processing

gem 'sinatra',              '1.4.5', require: nil # Lightweight web framework used by Sidekiq UI
gem 'foreman',              '0.77.0'              # Bundle the processes that need to be run concurrently

group :development, :test do
  gem 'hirb',               '0.7.3'               # Hirb improves ripl(irb)'s default inspect output.
  gem 'pry-rails',          '0.3.2'               # Pry is a powerful debugging shell for Ruby
  gem 'pry-doc',            '0.6.0'
  gem 'pry-byebug',         '3.0.1'
  gem 'rspec-rails',        '3.2.0'               # A testing framework for Rails
  gem 'quiet_assets',       '1.1.0'
end

group :test do
  gem 'faker',              '1.4.3'               # A library that generates fake data
  gem 'test_after_commit',  '0.4.0'               # NOTE: This is no longer needed on rails 5.0. Make after_commit callbacks fire in tests
  gem 'factory_girl_rails', '4.5.0'               # A fixtures replacement with a straightforward definition syntax
end

group :production do
  gem 'rails_12factor',     '0.0.3'
  gem 'font_assets',        '0.1.11'              # sets CORS headers correctly
end

group :alpine do
  # These versions must match EXACTLY the binary installed from the AlpineLinux apk
  # Otherwise bundler will try to native recompile which will fail horribly
  gem 'json',               '1.8.1'              
  gem 'nokogiri',           '1.6.5'
  gem 'pg',                 '0.17.1'
  gem 'timers',             '4.0.1'
end